# Generated by Django 4.0.5 on 2022-09-16 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='like_comment', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
